### ISSUE TITLE
Only emoji characters

### ISSUE THREAD

**Issue by mikeobank** [mikeobank/mnemojis#1]
Rephrase of an anonymous comment:

The numbers and Latin letters look somewhat off in between emoji symbols, particularly within strings like: 🎷🍖🪥💊⚡🛼🤡N📏🔌👋👗🦞🍣🪚V🐢V☀🤖🚽5⛰📎❤N🦴🫁🍖🧘🎲🌧. 

Wouldn't it look better to have a list of only emojis?

Also, maybe these emojis could be used as a replacement for some characters: 0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣🅰🅱🅾🅿

**Comment by mikeobank** [comment]
To achieve something similar rendering in the browser:
```CSS
/* dynamic: font-size, color, border & border-radius */
span {
  display: inline-block;
  box-sizing: border-box;
  width: 1em;
  height: 1em;

  text-align: center;
  font-size: 48px;
  font-weight: bold;
  line-height: 1em;

  color: white;
  text-shadow: 0px 0px 4px #005191;

  background: linear-gradient(180deg, #4db1ff, #008eff);
  border: 0.05em solid #008eff;
  border-radius: 0.05em;
}
``` 

Maybe not ideal, cause it requires wrapping each character of the string into `<span>` tags and also having to separate Latin chars vs. emojis.
